### PR TITLE
Extensibility model for content types

### PR DESCRIPTION
**Pull request by qmfrederik**
This pull requests implements an extensibility model for content types.

For example, if you want to add another content type that supports XML, you could do:

```
WebResponsFactory.SupportedContentTypes.Add("application/xml", WebResponseFactory.CreateXmlResponse);
```

There are, no doubt, tons of other ways of doing this, but it works for me.

The `HTML` responses are still hard coded; because they process the `<META>` tag and can trigger refreshes they were a bit of a special case.

### CODE REVIEW

**Comment by darrylwhitmore** [comment]
Hi Frederik, reviewing this, it looks like you are using C# 6 features (for the `SupportedContentTypes` property, maybe other places as well). You're ahead of me with that! While I do plan on moving to VS 2015, I don't really want to _have_ to do it just yet ;) Any way you could tweak this PR to make it compatible with C# 5?

**Comment by qmfrederik** [comment]
Hi Darryl,

Sure, I changed to project to default to C# 5.0 and removed the auto initializer.

Cheers!

**Comment by darrylwhitmore** [comment]
Great, thanks. Apologies for feet-dragging ;)

**Comment by darrylwhitmore** [comment]
Thanks again Frederik, this is a very nice piece of work and a great addition!

**Pull request merged**
