### PR TITLE
Support binary (`application/octet-stream`) content

### PR DESCRIPTION
**Pull request by qmfrederik**
Hi Darryl,

One more PR, this time to add for binary responses (of type `application/octet-stream`).
Should be pretty straightforward.

PS: I was wondering, do you plan to release a new version of the NuGet package any time soon?

Frederik.

### CODE REVIEW

**Comment by darrylwhitmore** [comment]
Hi Frederik, thanks again for the contribution!

I do want to cut another release and get out a NuGet update with all the new stuff you've added so far. Do you think you're at a point of stability, more or less, and that this would be a good point? If so, I'll turn my attention to that, just let me know.

**Comment by qmfrederik** [comment]
Hi Darryl,

I had a couple of user stories on my plate for which I needed NScrape; I've pretty much got them covered by now so I wouldn't expect any new major pull requests from my side. So from where I stand, this would be a great time to update the NuGet package ;-).

Cheers,

Frederik.

**Comment by darrylwhitmore** [comment]
Ok, sounds good, I'll turn my attention to a new release. Thanks!

**Comment by darrylwhitmore** [comment]
Finally got the release 0.2.0 NuGet package up, Frederik, it's available now!

**Comment by qmfrederik** [comment]
A bit late in replying, but thanks! Just upgrade to 0.2 and it works great for me, happy to be back on an official release ;-)

**Comment by darrylwhitmore** [comment]
Excellent, thanks again for all your contributions!

**Pull request merged**
