### PR TITLE
Add support for .NET Core

### PR DESCRIPTION
**Pull request by qmfrederik**
This PR aims to bring NScrape to .NET Core, a new member of the .NET family.

The changes basically boil down to:
- Using the new reflection API
- Using `.Dispose` instead of `.Close` on streams
- Accounting for the absence of (old-school) serialization
- Match the new `HttpWebRequest` and `HttpWebResponse` classes

It may make sense to have a closer look at the `HttpClientHandler` class as well, as some properties such as `AllowAutoRedirect` seem to have moved to that class, but I didn't get around doing that yet.

Let me know what you think.

### CODE REVIEW

**Comment by darrylwhitmore** [comment]
Hi again Frederik, I must admit that I am not up on .Net Core. I _did_ just move to VS.Net 2015 and C# 6, at least ;) 

I will read up on .Net Core to get a quick overview. I am guessing it is the future direction for .Net and that's why we'd want to get NScrape on-board?

I have been working on some changes in preparation for cutting another release; it seems like we've had enough changes since the last one and it's probably time. My initial thinking is that this new PR looks like it is significant enough to go into the next release, rather than tacking it onto the one I'm looking to make. That'd mean you'd need to resubmit it again, and deal with merging the changes I have pending now. I _am_ doing some refactoring of the recent cookie checking work; that'd probably be the most significant thing you'd have to deal with. How would that work for you? 

Would you rather see this PR added to the next release? I guess I'm fairly flexible if you would prefer that; I do not have really strong feelings about where to draw the line on a release. It just seemed like we had accumulated quite a few smallish changes and it was a good time. Let me know, and thanks again for all your work!

**Comment by qmfrederik** [comment]
Hi Darryl,

Well, I'm all for releasing soon, so a release containing the changes we have so far sounds good to me :+1: 

I think the jury is still out on whether .NET Core is "the" future of .NET, but it most certainly is part of the .NET future, at least for ASP.NET and cross-platform. We're adding Linux support to the project we're working on, so that's why I also took the time to port NScrape to .NET Core.

Let me know to which branch you want me to issue a pull request, and I'd be happy to create a new one.

PS: I noticed you don't have a CI (AppVeyor or Travis) set up for NScrape yet, would you want me to include a Travis build file in the PR as well?

**Comment by darrylwhitmore** [comment]
Hi Frederik, OK, I will work on wrapping up my current changes, get them committed, and cut the next release. You can then do your PR again on the **development** branch as usual. Hopefully merging my changes won't be too painful for you.

And yes, please do add CI configuration, that is an excellent idea. Here again, I'm behind the curve; we do use CI where I work and I understand it conceptually, but have not been involved in setting it up or configuring it (it's a frightening mass of XML). As such I don't have a preference, so feel free to configure for whichever one you prefer (or both if that works and is helpful). Thanks for pulling me along into stuff I should have picked up already ;)

**Comment by darrylwhitmore** [comment]
Frederik, profuse apologies, but I've finally committed my changes and cut the 0.3.0 release (and published the NuGet package). 

It all started innocently; I added some tests for the new cookie header parsing functionality. I hit some test failures, and tweaked the code. This happened a few more times and then I got the bright idea to rewrite the cookie parsing functionality using [Sprache](https://github.com/sprache/Sprache), which I've been looking for an excuse to use. Classic scope creep. Add in a very busy summer with a lot going on for us, and things just dragged on and on. 

Apologies once more. I shall not let it happen again!

**Comment by qmfrederik** [comment]
Hi @darrylwhitmore 

Visual Studio 2017 was released today, and with it an updated version of .NET Core.

I've taken the opportunity to rebase this PR against the latest version of NScrape (no more merge conflicts, yay!) and also update the .NET Core port.

For now, there's a CoreCompat.NScrape folder contains a C# project. This project builds for .NET Core and .NET 4.5 and is capable of creating a NuGet package as well.

If for some reason you cannot take the project files, I can remove them from this PR so you just have the code changes that allow NScrape to build for .NET Core.

Let me know what you think.

**Comment by darrylwhitmore** [comment]
Hi again Frederik! Dumb question, I'm still on VS 2015, assuming I would need to upgrade? I wouldn't be able to load the solution with the older Visual Studio, would I? I've been using Core with VS 2015 in conjunction with a Web API Pluralsight course that I've been working through, but I understand that the project file (project.json) is changing back, or something, so I'm in general still a bit confused about Core.

**Comment by qmfrederik** [comment]
@darrylwhitmore Yeah, the `project.json` file is gone and is replaced by a new `.csproj` file.

You can only open the new `.csproj` files with Visual Studio 2017, although you can use the command line to build it.

There's nothing that keeps us from having _both_ the VS2015 and VS2017 project files in parallel, though. Might that work for you?

**Comment by darrylwhitmore** [comment]
Well I will want to move to VS 2017, but ideally, I'd prefer not to _have_ to move until ready :) And it would also be best not to force anyone else who has the source to do move. So, yes, preserving the VS 2015 project would be great if you wouldn't mind doing it. Would it have a different name, because it looks like the extension is the same...?

**Comment by qmfrederik** [comment]
Hi Darryl,

Well, this PR would just add a `NScrape\NScrape.Core.csproj` file, so that can live next to the `NScrape\NScrape.csproj` file that you already have. Would that work OK for you?

**Comment by darrylwhitmore** [comment]
That sounds very good. Sorry, I inadvertently closed with my last comment! It'll probably be a few days before I can get to this. I see you've had a flurry of activity, so if you're not quite done, feel free to continue committing. This PR has been out so long (mostly due to my scope creep last summer!), I'm looking forward to getting it closed.

**Comment by qmfrederik** [comment]
Sure, I'll probably update the branch a couple of times more. I don't think there will be significant changes but I'll let you know when I think this is ready to merge :)

**Comment by qmfrederik** [comment]
Hi Darryl,

OK - I think this is ready for review. I squashed the commits so they should be easier to digest now.
I've also added an `.editorconfig` file because I kept mixing spaces and tabs.
I've also added an `appveyor.yml` file so you can enable AppVeyor builds if you want. It builds a NuGet package based on .NET Core - have a look at the output here: https://ci.appveyor.com/project/qmfrederik/nscrape/build/artifacts

Only things I can think of is that the .NET Core builds are not strongly named, and the generated NuGet package is also missing the icon - nothing that we cannot handle on a separate PR if needed :)

**Comment by darrylwhitmore** [comment]
Hi Frederik, I have installed VS 2017, pulled down the latest source with your changes, and loaded up the original NScrape.sln without any issues. However, when I closed that and tried to open NScrape.Core.sln, I got this warning, and cancelled in fear:

```
One-way upgrade
Visual Studio will automatically make functional changes to the following projects in order to open them. You will not be able to open these projects in the version of Visual Studio in which they were originally created.
	 - NScrape, "D:\GithubRoot\NScrape\NScrape\NScrape.xproj"


Non-functional changes required
Visual Studio will automatically make non-functional changes to the following projects in order to enable them to open in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1. Project behavior will not be impacted.
	 - NScrape.Core, "D:\GithubRoot\NScrape\NScrape.Core.sln"


No changes required
These projects can be opened in Visual Studio 2015, Visual Studio 2013, Visual Studio 2012, and Visual Studio 2010 SP1 without changing them.
	 - .nuget, ".nuget"
```

I'm a bit confused...I followed the link to "learn more", but maybe you can give me a quick explanation and recommendation? Apologies for being lazy; long day, I don't have any mental bandwidth left :)

**Pull request merged**
